---
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
  when: ansible_pkg_mgr == 'yum'
  tags: nginx, install

- name: Install nginx
  yum:
    name: nginx
    state: present
  when: ansible_pkg_mgr == 'yum'
  tags: nginx, install

- name: Install nginx
  apt:
    name: nginx
    state: present
  when: ansible_pkg_mgr == 'apt'
  tags: nginx, install

- name: Insert Index Page
  template:
    src: templates/index.html
    dest: /var/www/html/index.html
    mode: u=rw,g=r,o=r
  tags: nginx

- name: Insert Index Page
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
  tags: nginx

- name: Start NGiNX
  service:
    name: nginx
    state: started
  tags: nginx
