- hosts: ansiblemaster
  become: true
  vars:
    jenkins_hostname: localhost
    jenkins_version: "2.257"
    java_packages:
      - openjdk-8-jdk
    jenkins_plugins:
      - blueocean
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
